![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np
print(np.__version__)

1.21.6


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [2]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [3]:
x = np.full((3,3), True)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [4]:
print(my_array)
mask = (my_array % 2 == 1) 
print(mask)
print(my_array[mask])

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [5]:
type(mask)

numpy.ndarray

In [ ]:
my_array[my_array % 2 == 1]

In [6]:
lista_impares = []
for elem in my_array:
    if elem % 2 == 1:
        lista_impares.append(elem)
print(np.array(lista_impares))

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [8]:
my_array = np.arange(10)
nuevo_array = my_array.copy()


print(nuevo_array)
print(nuevo_array % 2 == 1)
print(nuevo_array[nuevo_array % 2 == 1])

nuevo_array[(nuevo_array % 2 == 1)] = -1
print(nuevo_array)

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [9]:
my_array = np.arange(10)
nuevo_array = my_array.copy()

# & and
# | or
nuevo_array[(nuevo_array % 2 == 1) & (nuevo_array <= 5)] = -1
print(nuevo_array)

[ 0 -1  2 -1  4 -1  6  7  8  9]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [10]:
my_array = np.arange(10)

new_array = np.where(my_array % 2 == 1, -1, my_array)
print(new_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [12]:
my_array = np.arange(10)
print(my_array)
new_array = my_array.reshape((2,5))
print(new_array)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [15]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print("-"*10)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
----------
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [16]:
np.concatenate((a, b), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.concatenate((a, b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [18]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [25]:
newnp = np.stack((a,b), axis = 0)
print(newnp)

[[[0 1 2 3 4]
  [5 6 7 8 9]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]


In [24]:
newnp[0]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [26]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [28]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [29]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
my_array_2 = my_array * 10
print(my_array_2)
print(my_array)

[ 0 10 20 30 40 50 60 70 80 90]
[0 1 2 3 4 5 6 7 8 9]


In [31]:
my_array[0]

0

In [32]:
my_array[-1]

9

In [33]:
my_array[1:8]

array([1, 2, 3, 4, 5, 6, 7])

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [34]:
my_matrix = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(my_matrix)

print(my_matrix.shape)
print(my_matrix.ndim)
print(my_matrix.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [35]:
np.arange(1,50,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [ ]:
np.arange(4,1,-0.25)

## Ejercicio 16
Lee la imagen "numpy.png"

In [ ]:
from skimage.io import imread
import matplotlib.pyplot as plt

imagen = imread("./img/numpy.png")
print(imagen.shape)

plt.imshow(imagen)

In [ ]:
imagen[200][100] # Pixel en la fila 200 y columna 100 con sus 4 Capas de RGB + Transparencia (solo en .png)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [36]:
# x = np.arange(4).reshape(4,1)
x = np.array([[1],
            [2],
            [3],
            [4]])
print(x)
x.reshape(2,2)

[[1]
 [2]
 [3]
 [4]]


array([[1, 2],
       [3, 4]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [ ]:
np.random.seed(6)
np.random.randint(10, 20, size=(4,5,3))

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [40]:
np.full((10,1), False).reshape(2,5)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [41]:
x = np.random.randint(10,20, size = (5,2,6))
print(x)

print(x.size)
print(x.ndim)
print(x.shape)

[[[19 12 14 10 14 16]
  [17 14 18 16 17 15]]

 [[12 15 10 12 10 11]
  [14 11 12 18 19 18]]

 [[18 15 18 10 18 12]
  [18 17 10 13 19 18]]

 [[13 14 16 11 11 11]
  [16 17 19 16 13 10]]

 [[15 13 15 16 19 12]
  [16 12 13 17 13 19]]]
60
3
(5, 2, 6)
