![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [5]:
import numpy as np

my_array = np.arange(10)

print(my_array)
print(my_array[::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [7]:
print(my_array)
print(my_array[-2:-4:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [9]:
print(my_array)
print(my_array[2::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [10]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [13]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [14]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [16]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
my_matrix[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [18]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [24]:
# my_matrix[start_filas:stop_filas:step_filas,start_columnas:stop_columnas:step_columnas]

In [23]:
my_matrix[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [2]:
import numpy as np

In [3]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [4]:
print(my_matrix[:-1:,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


In [5]:
print((my_matrix[:3,::-1]))

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [7]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x)

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']


In [10]:
# Mascara
mask = (x == "Loro")
print(mask)

print(x[mask])
print(x[x == "Loro"])

[ True False False  True False]
['Loro' 'Loro']
['Loro' 'Loro']


In [11]:
# Where
mask = np.where(x == "Loro", True, False)
print(mask)
print(x[mask])

[ True False False  True False]
['Loro' 'Loro']


In [13]:
np.where(x == "Loro", "Loro","")

array(['Loro', '', '', 'Loro', ''], dtype='<U4')

In [14]:
x[np.where(x=='Loro')]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [18]:
x = np.arange(20).reshape(2,5,2)
print(x)
print(x.ndim)
print(x.shape)
print(x.size)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
3
(2, 5, 2)
20


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [39]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [40]:
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [26]:
x = np.zeros(10)
print(x)

print(x.itemsize) # Cada elemento en bytes
print(x.nbytes) # El array en bytes
print(x.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8
80
float64


In [27]:
x[3] = 1
print(x)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [29]:
x = np.arange(10, 50)
print(x)
print(x[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [31]:
x = np.array([1,2,0,0,4,0])
y = np.nonzero(x)
print(y)

(array([0, 1, 4], dtype=int64),)


In [48]:
print(y[0])
y[0]

[0 1 4]


array([0, 1, 4], dtype=int64)

In [36]:
def ejercicio_13(x):
    y = np.nonzero(x)
    return y[0]

In [37]:
ejercicio_13([1,2,0,0,4,0])

array([0, 1, 4], dtype=int64)

In [38]:
ejercicio_13([1,5,0,2,4,0])

array([0, 1, 3, 4], dtype=int64)

In [46]:
x = "hola"
print(x)
x

hola


'hola'

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [65]:
np.random.seed(1234)
x = np.random.randint(100, size=(10,10))
print(x)

[[47 83 38 53 76 24 15 49 23 26]
 [30 43 30 26 58 92 69 80 73 47]
 [50 76 37 34 38 67 11  0 75 80]
 [ 3  2 19 12 65 75 81 14 71 60]
 [46 28 81 87 13 96 12 69 95 31]
 [89 84 45 16 41 72 56 70 56 86]
 [44 90 83 47 49 18 85 46 98 37]
 [38  7 67  5 47 47 15 34 10 28]
 [ 4 82 89 55 78 23 50 62 55 84]
 [ 0 98 90 33 21 71 68 81 52 64]]


In [69]:
print(x.min())
print(np.min(x))
# print(min((x)))
print(x.max())
print(np.max(x))


0
0
98
98


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [71]:
x = np.random.random(30)
print(x)

[0.15893009 0.94338268 0.76316153 0.05387827 0.25408163 0.92797263
 0.8383115  0.15692453 0.69077595 0.36694644 0.93747272 0.61336482
 0.69934982 0.50294625 0.7111109  0.13438585 0.82893194 0.74284587
 0.45703374 0.07910336 0.37304659 0.93363636 0.41872481 0.23421157
 0.57248483 0.57211088 0.41689298 0.62588308 0.22036227 0.62205913]


In [74]:
print(x.mean())
print(np.mean(x))
print(x.sum()/len(x))

0.5283441013576723
0.5283441013576723
0.5283441013576723


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [81]:
x = np.ones((8,8))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [82]:
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [83]:
def ejercicio_16(size):
    x = np.ones(size)
    x[1:-1,1:-1] = 0
    return x

In [85]:
ejercicio_16((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [88]:
x = np.zeros((8,8))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [89]:
# x[inicio_filas:final_filas:pasos_filas, inicio_columnas:final_columnas:pasos_columnas]
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [91]:
a = np.array([[0,1],[1,0]])
print(a)

[[0 1]
 [1 0]]


In [94]:
x = np.tile(a, (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [100]:
x = np.random.randint(1,20, (5,5))
print(x)

[[16 13 13  2  5]
 [ 6 10 18 15  7]
 [ 4 16 13 11 15]
 [17 13 17  3  4]
 [15  2  7  2  4]]


In [101]:
x = (x - np.mean(x)) / np.std(x)
print(x)

[[ 1.10722019  0.56089444  0.56089444 -1.44229998 -0.89597423]
 [-0.71386565  0.01456869  1.47143735  0.9251116  -0.53175706]
 [-1.07808281  1.10722019  0.56089444  0.19667727  0.9251116 ]
 [ 1.28932877  0.56089444  1.28932877 -1.26019139 -1.07808281]
 [ 0.9251116  -1.44229998 -0.53175706 -1.44229998 -1.07808281]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [102]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [103]:
y = x.copy()

y[(y > 3) & (y < 8)] = -1
print(y)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [105]:
y = x.copy()

y[(y > 3) & (y < 8)] *= -1
print(y)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
